name: bubble_todo_list

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^15.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^4.0.0
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.0
  json_annotation: ^4.9.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  modal_bottom_sheet: ^3.0.0
  connectivity_plus: ^6.1.0
  retry: ^3.1.2
  intl: ^0.20.2
  permission_handler: ^11.0.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_generator: ^2.0.0
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true